[build]
  command = "npm run build"   # Build command
  publish = "build"           # Output directory
  branch = "main"             # Git branch to deploy

[build.environment]
  NODE_VERSION = "16"         # Environment variable

[[redirects]]
  from = "/*"                 # Handle all routes
  to = "/index.html"
  status = 200


[build]
  command = "npm run build"



