[build]
  command = "npm run build"   # Your build command
  publish = "build"           # The directory to deploy (React uses 'build')
  branch = "main"             # Your Git branch for deployment

[build.environment]
  NODE_VERSION = "16"         # Ensure Node.js version matches your project


[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

[build]
  command = "npm run build"
  publish = "dist"



